blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('data_app.urls', namespace='salon'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/data_app/urls.py
from django.urls import path
from data_app import views



app_name = 'data_app'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('post/<int:id>', views.post, name='post'),
    path('service/', views.service, name='service'),
    path('hairdresser/', views.hairdresser, name='hairdresser'),
    path('booking/', views.booking, name='booking'),
    path('contacts/', views.contacts, name='contacts')
]

blog/data_app/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class Profession(models.Model):
    """
     профессии
    """
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(blank=True)
    actual = models.BooleanField(default=True)

    def __str__(self):
        return self.name

def get_default_profession():
    #в первой строке таблицы profession помещена запись
    # для дефолтного случая (без реальной ссылки)
    return 1


class Staff(models.Model):
    """
    данные о персонале
    """
    name = models.CharField(max_length=32)
    first_name = models.CharField(max_length=32)
    middle_name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    mail = models.EmailField(blank=True)
    phone = PhoneNumberField(null=True, blank=True)
    profession = models.ForeignKey(Profession, null=True, on_delete=models.CASCADE)
    actual = models.BooleanField(default=True)
    portrait = models.ImageField(upload_to='staff', null=True, blank=True)

    def __str__(self):
        s = '' + self.first_name + ' ' + self.name
        return s


class Client(models.Model):
    """
    данные о клиентах
    """
    name = models.CharField(max_length=32, blank=True)
    first_name = models.CharField(max_length=32, blank=True)
    middle_name = models.CharField(max_length=32, blank=True)
    pseudonym = models.CharField(max_length=32, blank=True)
    sex = models.BooleanField(blank=True)
    mail = models.EmailField(blank=True)
    telegram_id = models.CharField(max_length=16, blank=True)
    phone = PhoneNumberField(null=True, blank=True)
    description = models.TextField(blank=True)
    actual = models.BooleanField(default=True)

    def __str__(self):
        s = '' + self.name + '_/_' + self.first_name
        return s


class Room(models.Model):
    """
     комнаты
     поле sex - комната для мужчин (=True),
                        для женщин (=False)
                        для всех   (=None)
    """
    name = models.CharField(max_length=32, unique=True)
    sex = models.BooleanField(null=True, default=None)
    description = models.TextField(blank=True)
    in_use = models.BooleanField(null=True, default=True)

    def __str__(self):
        return self.name


class Procedure(models.Model):
    """
     список процедур
    """
    name = models.CharField(max_length=32, unique=True)
    profession = models.ForeignKey(Profession, null=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    dt = models.DurationField(blank=True, null=True)
    actual = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class TimetableStatus(models.Model):
    """
     статус записи в расписании
    """
    name = models.CharField(max_length=32, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class WorkingTime(models.Model):
    """
     таблица рабочего времени с шагом 10 минут
    """
    staff = models.ForeignKey(Staff, null=True, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    ready = models.BooleanField(default=False)

class TimeTable(models.Model):
    """
    Расписание загруженности мастеров и помещений
    """
    start_time = models.DateTimeField()
    procedure = models.ForeignKey(Procedure, null=True, on_delete=models.CASCADE)
    spec_requirements = models.TextField(blank=True, null=True)
    client = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)      # клиент, сделавший заказ
    client_req_time = models.DateTimeField(blank=True, null=True)                           # время размещения заказ
                                                                                 # сотрудник, подтвердивший заказ
    staff_confirm = models.ForeignKey(Staff, related_name='tt_confirm', null=True, on_delete=models.CASCADE)

    staff_req_time = models.DateTimeField(blank=True, null=True)                            # время подтверждения заказа
                                                                                 # сотрудник, выполняющй заказ
    staff_worker = models.ForeignKey(Staff, related_name='tt_worker', null=True, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, null=True, on_delete=models.CASCADE)
    status = models.ForeignKey(TimetableStatus, null=True, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)


class News(models.Model):
    """
    Новости для размещения на главную страницу
    """
    name = models.CharField(max_length=126, unique=True)
    description = models.TextField(blank=True)
    full_text = models.TextField(blank=True)
    photo = models.ImageField(upload_to='news', null=True, blank=True)
    day = models.DateField(blank=False)

    def __str__(self):
        return self.name

blog/data_app/forms.py
from django import forms
from phonenumber_field.modelfields import PhoneNumberField
from .models import Staff, Procedure, TimeTable

class BookingForm(forms.Form):

    hairdresser = forms.ModelChoiceField(queryset=Staff.objects.exclude(name='default').all(), label='мастер ', required=False)
    service = forms.ModelChoiceField(queryset=Procedure.objects.exclude(name='default').all(), label='услуга ', help_text = '*')
    booking_day = forms.DateField(label='Удобная для Вас дата ', help_text='*', initial='02.01.2023')
    booking_time = forms.TimeField(label='Удобное для Вас время ', help_text='*', initial='15:30')
    remark = forms.CharField(label='Дополнительные пожелания ', required=False)
    customer = forms.CharField(label='Как к Вам обращаться? ', help_text='*')
    contact = forms.CharField(label='Как с Вами связаться (телефон/email)? ', help_text='*')

blog/data_app/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.mail import send_mail
from django.urls import reverse
from .models import News, Procedure, Staff
from .forms import BookingForm
from .support_func import make_letter_text

# Create your views here.

def main_view(request):
    last_news = 2
    posts = News.objects.order_by('-day')[:last_news]
    return render(request, 'data_app/index.html', context={'posts': posts})

def post(request, id):
    post = get_object_or_404(News, id=id)
    return render(request, 'data_app/post.html', context={'post': post})

def service(request):
    posts = Procedure.objects.exclude(name='default').all()
    return render(request, 'data_app/service.html', context={'posts': posts})

def hairdresser(request):
    staff = Staff.objects.exclude(name='default').all()
    return render(request, 'data_app/hairdresser.html', context={'posts': staff})

def booking(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            booking_order = {}
            booking_order['hairdresser'] = form.cleaned_data['hairdresser']
            booking_order['service'] = form.cleaned_data['service']
            booking_order['booking_day'] = form.cleaned_data['booking_day']
            booking_order['booking_time'] = form.cleaned_data['booking_time']
            booking_order['remark'] = form.cleaned_data['remark']
            booking_order['customer'] = form.cleaned_data['customer']
            booking_order['contact'] = form.cleaned_data['contact']

            send_mail('Новый заказ',make_letter_text(booking_order),
                      '7900953@gmail.com', ['nik_agafonov@icloud.com'],
                      fail_silently=False)



            return HttpResponseRedirect(reverse('salon:index'))

        else:
            return render(request, 'data_app/booking.html', context={'form': form})
    else:
        form = BookingForm()
        return render(request, 'data_app/booking.html', context={'form': form})

def contacts(request):
    pass
    return render(request, 'data_app/contacts.html')

blog/data_app/templates/data_app/booking.html
{% extends 'base.html' %}

{% block title %}
Бронировать
{% endblock %}

{% block main_content %}

        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <h2>Бронирование услуг</h2>
                        <div class="my-5">
                            <form method='post' id="bookingForm">
                                {% csrf_token %}
                                {{form.as_p}}
                                <i>обязательно для заполнения  *</i> <br><br>
                                <button class="btn btn-primary" id="sendMessageButton" type="submit">Отправить запрос</button>
                                <br>
                                <p class="post-subtitle">или позвоните нам: +7 495 333 22 11</p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
 {% endblock %}

blog/data_app/templates/data_app/contacts.html
{% extends 'base.html' %}

{% block title %}
Контакты
{% endblock %}

{% block main_content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <h2 class="post-title"> Наш адрес: </h2>
                    <h2 class="post-title">  </h2>
                    <p class="post-subtitle"> г. Москва, ул. Цирюльная, дом 13</p>
                    <a href="https://www.yelp.com/map/hi-tech-barber-shop-cupertino" > <img src="/static/assets/img/map.jpg" height="255"></a>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <h2 class="post-title"> Телефон: </h2>
                    <h2 class="post-title">  </h2>
                    <p class="post-subtitle"> +7 495 333 22 11</p>

                 </div>
            </div>
        </div>

{% endblock %}


<!--https://www.yelp.com/map/hi-tech-barber-shop-cupertino-->

blog/data_app/templates/data_app/hairdresser.html
{% extends 'base.html' %}

{% block title %}
Мастера
{% endblock %}

{% block main_content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for item in posts %}
                    <div class="post-preview">
<!--                        <a href="post.html">-->
                        <a>
                            <img src="{{item.portrait.url}}" height="250">
                            <h2 class="post-title">{{ item.first_name }} {{ item.name }} </h2>
                            <h2 class="post-title">  </h2>
                            <h3 class="post-subtitle"> {{ item.description }}</h3>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Post preview-->
                    {% endfor %}

                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="{% url 'salon:booking' %}">Забронировать услугу →</a>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

blog/data_app/templates/data_app/index.html
{% extends 'base.html' %}

{% block title %}
QWERTY
{% endblock %}

{% block main_content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for item in posts %}
                    <div class="post-preview">
                        <a href="{% url 'salon:post' id=item.id %}">
                            <h2 class="post-title"> {{ item.name }} </h2>
                             <h2 class="post-title">  </h2>
                            <h3 class="post-subtitle"> {{ item.description }}</h3>
                            <h3 class="post-subtitle"> {{ item.day }} </h3>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Post preview-->
                    {% endfor %}

                </div>
            </div>
        </div>

{% endblock %}

blog/data_app/templates/data_app/post.html
{% extends 'base.html' %}

{% block title %}
Подробно
{% endblock %}

{% block main_content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% if post %}
                    <div class="post-preview">
<!--  расширения новостей пока не предвидится  <a href="post.html">-->
                        <a>
                            <h2 class="post-title"> {{ post.name }} </h2>
                            <h2 class="post-title">  </h2>
                            <img src="{{post.photo.url}}" height="250">
                            <h3 class="post-subtitle"> {{ post.full_text }}</h3>
                            <h3 class="post-subtitle"> {{ post.day }} </h3>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Post preview-->
                    {% endif %}

                    <!-- Pager-->
<!--                    <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Еще новости →</a></div>-->
                </div>
            </div>
        </div>

{% endblock %}

blog/data_app/templates/data_app/service.html
{% extends 'base.html' %}

{% block title %}
Услуги
{% endblock %}

{% block main_content %}
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <!-- Post preview-->
                    {% for item in posts %}
                    <div class="post-preview">
<!--                        <a href="post.html">-->
                        <a>
                            <h2 class="post-title"> {{ item.name }} </h2>
                             <h2 class="post-title">  </h2>
                            <h3 class="post-subtitle"> {{ item.description }}</h3>
                        </a>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />

                    <!-- Post preview-->
                    {% endfor %}

                    <!-- Pager-->
                    <div class="d-flex justify-content-end mb-4">
                        <a class="btn btn-primary text-uppercase" href="{% url 'salon:booking' %}">Забронировать услугу →</a>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

blog/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>{% block title %}{% endblock %}</title>

        <link rel="icon" type="image/x-icon" href="{% static 'assets/q_im.jpeg' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="https://omchairworld.com">Всемирная Организация Парикмахеров</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'salon:index' %}">Главная</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'salon:service' %}">Услуги</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'salon:hairdresser' %}">Мастера</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'salon:booking' %}">Запись</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'salon:contacts' %}">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('static/assets/img/home-bg.jpeg')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Салон красоты QWERTY</h1>
                            <span class="subheading">лазерная стрижка</span>
                            <span class="subheading">цифровой массаж</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>

                    {% block main_content %}{% endblock %}


        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>